---
- hosts: localhost
  become: true

  tasks:
    - hostname:
        name: laPtak
    - include: tasks/users.yml
    - include: tasks/ssh.yml
    - include: tasks/trash.yml
    - include: tasks/crontab.yml
    - include: tasks/sudoers.yml
      #    - include: tasks/repositories.yml
    - include: tasks/packages.yml
      #- include: tasks/flatpak.yml
      #- include: tasks/kde.yml
      #- include: tasks/bitwarden.yml
      #- include: tasks/onedrive.yml
      #- include: tasks/bumblebee.yml


