- name: install cron job (szydell, clear trash)
  cron: user="szydell" name="clear trash" hour="*/1" job="/usr/bin/find $HOME/{Downloads,Documents,Pictures,Video}/trash/* -mtime +6 -type f -delete"

- name: install cron job (szydell, clear Downloads)
  cron: user="szydell" name="clear Downloads" hour="*/1" job="/usr/bin/find $HOME/Downloads* -mtime +30 -type f -delete"

- name: keep known_hosts up to date
  cron:
   user: "szydell"
   name: "known_hosts updater"
   job: "ansible-vault --vault-password-file ~/.config/lapsible_vaultpass encrypt ~/.ssh/known_hosts --output ~/development/lapsible/files/known_hosts && cd ~/development/lapsible && git add files/known_hosts && git commit -m 'known_hosts updater' files/known_hosts && git push"
   special_time: "daily"

