
- name: Check if VSCode is installed
  command: dpkg-query -W code
  register: vscode_check_deb
  failed_when: vscode_check_deb.rc > 1
  changed_when: vscode_check_deb.rc == 1

- name: Download VS Code
  get_url: 
    url="https://go.microsoft.com/fwlink/?LinkID=760868"
    dest="/home/{{ ansible_env.USER }}/Downloads/code.deb"
  when: vscode_check_deb.rc == 1

- name: Install VS Code
  apt: deb="/home/{{ ansible_env.USER }}/Downloads/code.deb"
  become: true
  when: vscode_check_deb.rc == 1


#- name: Install packages
#  dnf:
#    name: ['@Development tools', 'arduino', 'esptool', 'nmap', 'snapd', 'htop', 'mc', 'vim', 'golang', 'flatpak', 'gcompris', 'gcompris-qt-activities', 'code', 'strace', 'vlc-extras', 'libcurl-devel', 'sqlite-devel', 'NetworkManager-tui','VirtualBox','steam','fedora-workstation-repositories']
#    state: present

