
- name: Check if VSCode is installed
  command: dpkg-query -W code
  register: vscode_check_deb
  failed_when: vscode_check_deb.rc > 1
  changed_when: vscode_check_deb.rc == 1

- name: Download VS Code
  get_url: 
    url="https://go.microsoft.com/fwlink/?LinkID=760868"
    dest="/home/szydell/Downloads/code.deb"
  become: true
  become_user: "szydell"
  when: vscode_check_deb.rc == 1

- name: Install VS Code
  apt: deb="/home/szydell/Downloads/code.deb"
  when: vscode_check_deb.rc == 1


- name: Install packages
  apt:
    name: ['unifi','virtualbox-ext-pack','steam','browser-plugin-freshplayer-pepperflash','vlc','gcompris','vim','mc','golang-go','snapd','arduino','esptool','dconf-editor','nmap','htop','flatpak']


